# Install Hello World Application
- name: Install Hello World Application
  hosts: myservers
  become: true
  vars: 
    app_destination: /home/ec2-user/
  tasks: 
    -name: create application directory
     file:
       path: "{{ app_destination }}" 
       state: directory
    -name: Create index.html file 
     copy:
       content: "Hello World"
       dest: "{{ app_destination }}/index.html"
